---
kind: pipeline
name: build

clone:
  depth: 1

workspace:
  base: /go
  path: src/yunion.io/x/onecloud-operator

steps:
- name: build
  image: golang:latest
  commands:
  - make build

- name: image-dev
  image: plugins/docker
  settings:
    repo: registry.cn-beijing.aliyuncs.com/yunionio/onecloud-operator
    registry: registry.cn-beijing.aliyuncs.com
    dockerfile: images/onecloud-operator/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - latest
    - "${DRONE_COMMIT_SHA:0:8}"

- name: image
  image: plugins/docker
  settings:
    repo: registry.cn-beijing.aliyuncs.com/yunionio/onecloud-operator
    registry: registry.cn-beijing.aliyuncs.com
    dockerfile: images/onecloud-operator/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: "${DRONE_TAG}"
  when:
    event:
    - tag
